name: xServer
main: cbp.double0negative.xServer.XServer
authors: [double0negative, MCForger, Stoolbend, Kealper]
version: ${project.version}
commands:
  xserver:
    description: Stats and controls for xserver
    usage: /XServer command or /x command
    aliases: [x]
permissions:
  xserver.message.receive:
    description: Allows the player to receive xServerChat messages
    default: true
  xserver.message.send:
    description: Allows the player to send xServerChat messages
    default: true
  xserver.message.cancelled:
    description: Allows the player to be notified of cancelled chat messages
    default: op
  xserver.admin:
    description: Allows the player to configure xServerChat
    default: op