name: xServerPM
main: xServerPM\xServerPM
version: 1.2.1
api: 3.0.0-ALPHA7
author: Kealper
depend: [PureChat, SimpleAuth]

commands:
  xserver:
    description: Main xServerPM command
    usage: "/xserver <args>"
  helpop:
    aliases: [ac]
    description: Emulates Essentials' helpop command for PMMP
    usage: "/helpop <message to send>"
  opchat:
    aliases: [a]
    description: Separate chat channel for server ops
    usage: "/opchat <message to send>"
